# Generated by Django 4.0.3 on 2024-04-15 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=10)),
                ('Rate', models.FloatField()),
                ('Location', models.CharField(max_length=20)),
                ('Squarefeet', models.CharField(max_length=10)),
                ('NoofBeds', models.IntegerField()),
                ('NoofBathrooms', models.IntegerField()),
                ('Facing', models.CharField(max_length=20)),
                ('Description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='properyListdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Listdetail', models.CharField(max_length=100)),
                ('propertyrel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propertiesServer14.property')),
            ],
        ),
    ]
