# Generated by Django 4.0.3 on 2024-04-15 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propertiesServer14', '0002_remove_properylistdetails_propertyrel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='propertyrel',
        ),
        migrations.AddField(
            model_name='properylistdetails',
            name='propertyrel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properyListdetails', to='propertiesServer14.property'),
        ),
        migrations.AlterField(
            model_name='property',
            name='Description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='Facing',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='Location',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='Name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='NoofBathrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='NoofBeds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='Rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='Squarefeet',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='properylistdetails',
            name='Listdetail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
