# Generated by Django 4.0.3 on 2024-04-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertiesServer14', '0004_properylistdetails_propimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='Video',
            field=models.FileField(blank=True, default=None, null=True, upload_to='videos'),
        ),
    ]
