# Generated by Django 4.0.3 on 2024-04-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertiesServer14', '0006_alter_property_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='PropertyType',
            field=models.CharField(choices=[('Sale', 'For Sale'), ('Rentel', 'For Rentel')], default='Sale', max_length=20),
        ),
    ]
