# Generated by Django 4.0.3 on 2024-04-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertiesServer14', '0007_property_propertytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='PropertyList',
            field=models.CharField(blank=True, choices=[('appartment', 'Apartment'), ('villa', 'Villa'), ('home', 'Home'), ('office', 'Office'), ('building', 'Building'), ('township', 'Township'), ('shop', 'Shop'), ('garage', 'Garage')], default='appartment', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='PropertyType',
            field=models.CharField(blank=True, choices=[('Sale', 'For Sale'), ('Rentel', 'For Rentel')], default='Sale', max_length=20, null=True),
        ),
    ]
