# Generated by Django 4.0.3 on 2024-04-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertiesServer14', '0008_property_propertylist_alter_property_propertytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='issold',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
