# Generated by Django 4.0.3 on 2024-04-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertiesServer14', '0009_property_issold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='Description',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='Facing',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='Location',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='Name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='NoofBathrooms',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='NoofBeds',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='Rate',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='Squarefeet',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
